### ISSUE TITLE
[CI] Run tests on big-endian and little-endian machines

### ISSUE THREAD

**Issue by BrendanChou** [commonwarexyz/monorepo#938]
Gemini gives the following instructions:

-----

For Rust projects where you want to test on big-endian architectures in GitHub Actions, the primary and most effective method is to use **emulation with QEMU**, often facilitated by tools like `cross`.

Here's a breakdown of how you can achieve this:

**1. Using `cross` for Cross-Compilation and Testing**

The `cross` tool is designed to make cross-compiling Rust projects easier. It uses Docker and QEMU behind the scenes to build and run your code for various target architectures, including big-endian ones.

  * **How it works:** `cross` pulls pre-configured Docker images that include the Rust toolchain and necessary emulators (like QEMU) for the specified target. When you run `cross test --target <your-big-endian-target>`, it compiles your code for that target and then runs the tests within an emulated environment.
  * **Supported Big-Endian Targets for Rust:**
      * `s390x-unknown-linux-gnu` (IBM Z, big-endian)
      * `powerpc64-unknown-linux-gnu` (PowerPC, big-endian)
      * `mips64-unknown-linux-gnuabi64` (MIPS big-endian)
      * `sparc64-unknown-linux-gnu` (SPARC big-endian)
      * ARM targets with big-endian variants (though less common for general testing, e.g., `armebv7r-none-eabi`). For Linux targets, `arm64_be-unknown-linux-gnu` might be an option if a suitable Docker image with QEMU support exists.

**2. Setting up GitHub Actions Workflow with `cross`**

Your GitHub Actions workflow file (e.g., `.github/workflows/ci.yml`) would typically involve these steps:

  * **Checkout your code:**
    ```yaml
    - uses: actions/checkout@v4
    ```
  * **Install Rust:** You might use `actions-rs/toolchain` or set it up manually.
    ```yaml
    - uses: dtolnay/rust-toolchain@stable
    ```
  * **Install `cross`:**
    ```yaml
    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross --rev main # Or use a tagged release
    ```
    *(Note: It's generally recommended to use a specific tagged release of `cross` for stability, e.g., `cargo install cross --version <latest_stable_version>` if available via crates.io, or a specific git tag/commit if installing from git).*
  * **Run tests for your standard little-endian target(s):** (e.g., `x86_64-unknown-linux-gnu`)
    ```yaml
    - name: Test (native)
      run: cargo test --verbose
    ```
  * **Run tests for big-endian target(s) using `cross`:**
    ```yaml
    - name: Test (s390x - big-endian)
      run: cross test --target s390x-unknown-linux-gnu --verbose

    - name: Test (powerpc64 - big-endian)
      run: cross test --target powerpc64-unknown-linux-gnu --verbose
    ```

**Example GitHub Actions Workflow Snippet:**

```yaml
name: Rust CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest # GitHub-hosted runners are little-endian (x86_64)
    strategy:
      matrix:
        rust: [stable] # You can matrix build for different Rust versions
        # Define your targets, including big-endian ones
        target:
          - x86_64-unknown-linux-gnu # Native little-endian
          - s390x-unknown-linux-gnu    # Big-endian via cross
          - powerpc64-unknown-linux-gnu # Big-endian via cross
          # Add other targets as needed

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }} # Ensures target components are available for cross-compilation if needed

      - name: Install cross (if target is not native)
        if: matrix.target != 'x86_64-unknown-linux-gnu' # Adjust if your native target is different
        run: cargo install cross --git https://github.com/cross-rs/cross --rev main # Or specific version

      - name: Run tests
        run: |
          if [ "${{ matrix.target }}" = "x86_64-unknown-linux-gnu" ]; then
            cargo test --verbose
          else
            cross test --target ${{ matrix.target }} --verbose
          fi
```

**3. Manual QEMU Setup (More Complex, Generally Not Needed if `cross` Works)**

If `cross` doesn't support a specific niche target or you need more fine-grained control, you could manually set up QEMU and a Docker container for your big-endian environment. This is more involved:

  * **Install QEMU user static:** This allows the host kernel to run binaries from other architectures.
    ```yaml
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    ```
  * **Use a Docker container for the big-endian architecture:** You'd find or build a Docker image for, say, `s390x` that includes Rust.
    ```yaml
    - name: Run tests in s390x container
      uses: docker://s390x/rust # Fictional image, you'd need to find a real one
      with:
        args: |
          bash -c "
          cd /path/to/your/project_in_container
          cargo test --verbose
          "
    ```
    This approach requires more setup to get your code into the container, install dependencies, and manage the environment. `cross` abstracts most of this complexity away.

**Key Considerations for Rust Big-Endian Testing:**

  * **Dependencies:** Ensure your crate's dependencies also compile and work correctly on big-endian systems. Most well-maintained core Rust crates are endian-neutral. However, C dependencies or crates doing low-level byte manipulation might have issues.
  * **Conditional Compilation (`#[cfg(target_endian = "big")]`):** If you have specific code paths for big-endian systems, use Rust's conditional compilation attributes to manage them. Your tests should then cover these paths when run on the emulated big-endian target.
  * **Test Coverage:** Write tests that specifically target areas of your code prone to endianness bugs (e.g., network protocol parsing, file format reading/writing, raw byte array manipulation).
  * **`cross` Docker Images:** `cross` relies on community-maintained Docker images. Ensure the image for your target is up-to-date and supports the Rust version you're using.
  * **Build Times:** Cross-compiling and running tests under emulation will generally be slower than native compilation and execution. Factor this into your CI run times.

By leveraging `cross`, you can integrate big-endian testing into your GitHub Actions workflows for your Rust projects without needing to manage self-hosted infrastructure, relying instead on the powerful combination of Docker and QEMU on GitHub's standard runners.
